# Generated by Django 6.0.2 on 2026-02-24 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dal_resources', '0003_activitylog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitylog',
            name='category',
            field=models.CharField(choices=[('user_management', 'User Management'), ('billing', 'Billing'), ('subscription', 'Subscription'), ('support', 'Support Ticket'), ('reports', 'Reports')], max_length=50),
        ),
    ]
