# Generated by Django 6.0.2 on 2026-03-04 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('disabled', 'Disabled'), ('deactivated', 'Deactivated'), ('archived', 'Archived')], default='active', max_length=20),
        ),
    ]
