# Generated by Django 6.0.2 on 2026-03-02 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0002_plan_alter_billing_plan_alter_subscription_plan'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscription',
            name='next_billing_date',
        ),
        migrations.AlterField(
            model_name='subscription',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('disabled', 'Disabled'), ('deactivated', 'Deactivated')], max_length=50),
        ),
    ]
