# Generated by Django 6.0.2 on 2026-03-04 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0004_alter_subscription_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymenthistory',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('voided', 'Voided')], default='pending', max_length=50),
        ),
    ]
