# Generated by Django 6.0.2 on 2026-03-08 19:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0005_alter_paymenthistory_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supportticket',
            name='is_archived',
        ),
    ]
