# Generated by Django 6.0.2 on 2026-03-09 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0006_remove_supportticket_is_archived'),
    ]

    operations = [
        migrations.AddField(
            model_name='supportticket',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
    ]
