# Generated by Django 6.0.2 on 2026-03-09 09:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0007_supportticket_is_archived'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ActivityLog',
        ),
    ]
