# Generated by Django 6.0.2 on 2026-03-24 08:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0008_delete_activitylog'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='billing',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='plan',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='subscription',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='supportticket',
            options={'ordering': ['id']},
        ),
    ]
